[project]
name = "mc-rag"
version = "0.1.0"
description = "Minecraft RAG 系统"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.8",
    "dotenv>=0.9.9",
    "langchain>=1.2.15",
    "langchain-deepseek>=1.0.1",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.2.1",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.1.9",
    "sentence-transformers>=5.4.1",
]
